---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: root
  become: False
  gather_facts: True

  roles:
    - common
    #- mailserver
    #- webmail
    #- blog
    #- ircbouncer
    #- xmpp
    #- owncloud
    #- vpn
    #- tarsnap
    #- news
    #- git
    #- readlater
    - monitoring  # Monitoring role should be last. See roles/monitoring/README.md

- hosts: ingress
  user: root
  become: False
  gather_facts: True

  roles:
    - common
    - role: monitoring
      vars:
        use_haproxy: True
