- import_tasks: postfix.yml
  tags: postfix
- import_tasks: dovecot.yml
  tags: dovecot
- import_tasks: rspamd.yml
  tags: rspamd
- import_tasks: solr.yml
  tags: solr
- import_tasks: checkrbl.yml
  tags: checkrbl
- import_tasks: z-push.yml
  tags: zpush
- import_tasks: autoconfig.yml
  tags: autoconfig

