- name: Create directory for blog HTML
  file: state=directory path=/var/www/{{ domain }} group=www-data owner={{ main_user_name }}

- name: Rename existing Apache blog virtualhost
  command: >-
    mv /etc/apache2/sites-available/{{ domain }} /etc/apache2/sites-available/{{ domain }}.conf
    removes=/etc/apache2/sites-available/{{ domain }}

- name: Remove old sites-enabled/{{ domain }} symlink (new one will be created by a2ensite)
  file: path=/etc/apache2/sites-enabled/{{ domain }} state=absent

- name: Configure the Apache HTTP server for the blog
  template: >-
    src=etc_apache2_sites-available_blog.j2
    dest=/etc/apache2/sites-available/{{ domain }}.conf
    group=root
    owner=root

- name: Enable blog site
  command: a2ensite {{ domain }}.conf creates=/etc/apache2/sites-enabled/{{ domain }}.conf
  notify: restart apache

