- name: import wallabag sql
  command: >-
    psql -h localhost -d {{ wallabag_db_database }} -U {{ wallabag_db_username }}
    -f /var/www/wallabag/install/postgres.sql --set ON_ERROR_STOP=1
  environment:
    PGPASSWORD: "{{ wallabag_db_password }}"
  notify: remove install folder

- name: remove install folder
  file: path=/var/www/wallabag/install state=absent
