---
- debug:
    msg: >-
      OwnCloud is not supported in this distribution release
      https://github.com/sovereign/sovereign/issues/765
  when: ansible_distribution_release in ["jessie", "trusty"]

- import_tasks: owncloud.yml
  tags: owncloud
  # https://github.com/sovereign/sovereign/issues/765
  when: ansible_distribution_release not in ["jessie", "trusty"]
